services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    restart: always
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      rabbitmq:
        condition: service_healthy 
      postgres.db:
        condition: service_started 
    ports:
        - "8001:8080"

  market.api:
    image: ${DOCKER_REGISTRY-}marketapi
    build:
      context: .
      dockerfile: Market.API/Dockerfile
    restart: always
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      rabbitmq:
        condition: service_healthy
      my-mongodb:
        condition: service_started
    ports:
        - "8002:8080"

  notifications.api:
    image: ${DOCKER_REGISTRY-}notificationsapi
    build:
      context: .
      dockerfile: Notifications.API/Dockerfile
    restart: always
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER} 
      - RabbitMQ__Password=${RABBITMQ_PASS}
      - EmailSettings__Password=${EMAIL_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres.db:
        condition: service_started
    ports:
        - "6000:8080"  

  portfolio.api:
    image: ${DOCKER_REGISTRY-}portfolioapi
    build:
      context: .
      dockerfile: Portfolio.API/Dockerfile
    restart: always
    environment:
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_USER}
      - RabbitMQ__Password=${RABBITMQ_PASS}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres.db:
        condition: service_started
    ports:
       - "7000:8080"

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: API.Gateway/Dockerfile
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    ports:
      - "5000:8080"

  postgres.db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=IdentityDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
       - postgres_data:/var/lib/postgresql/data

  my-mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo_data:/data/db

  redis:
     image: redis:6.2-alpine
     restart: always
     ports:
       - "6379:6379"
     container_name: redis_db
     environment:
       - REDIS_DATABASE=0
       - REDIS_USERNAME=${REDIS_USERNAME} 
       - REDIS_PASSWORD=${REDIS_PASSWORD}
     volumes:
       - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 15s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
    restart: always

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
  postgres_data:   