POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "UserName": "AnanasAvcisi",
  "FirstName": "Ýbrahim",
  "LastName": "Kabadayý",
  "Email": "ibrahimkabadayi180@gmail.com",
  "Password": "i1b3r9a8A*"
}