POST http://localhost:5000/api/wallets/625f4929-c158-4eed-878c-d0923aa6e9b2/assets/BTC
Content-Type: application/json
Idempotency-Key: test-key-dsg1hjddvddvss2gfhghuytte
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlmMTgxMi03MDYxLTdhMDUtODNmZi1mNzZiZWJjNThlMDYiLCJlbWFpbCI6ImlicmFoaW10ZXN0QGdtYWlsLmNvbSIsIm5hbWVpZCI6IjAxOWYxODEyLTcwNjEtN2EwNS04M2ZmLWY3NmJlYmM1OGUwNiIsImp0aSI6ImYyNWQwODA1LTc2YmQtNDU5My1hMDhjLWI2NjYxZTM2NTY4MiIsIm5iZiI6MTc4MjgxNTI5MCwiZXhwIjoxNzgyODIyNDkwLCJpYXQiOjE3ODI4MTUyOTAsImlzcyI6IklkZW50aXR5QVBJIiwiYXVkIjoiQ3J5cHRvQXBwVXNlcnMifQ.iYKRmb8lQ8XBP_NJSDi5mCAE2njv7OCDAKsUBExGrWA

{
  "BuyingPrice": 200000,
  "Amount": 0.02
}