POST http://localhost:5252/api/wallets/887f497a-7233-4083-80df-1607b0f2ce38/transaction
Content-Type: application/json
Idempotency-Key: test-key-127
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlkMTcwYS1mZjFhLTcyYzItYjViNC1kMjkxZTgwMDhmMWIiLCJlbWFpbCI6ImlicmFoaW10ZXN0QGdtYWlsLmNvbSIsImp0aSI6ImM1MjliNDVjLThlOTktNDI4Zi1iY2QxLWE3YzdkZTJiM2MxOSIsIm5iZiI6MTc3OTA5NDU3NiwiZXhwIjoxNzc5MTAxNzc2LCJpYXQiOjE3NzkwOTQ1NzYsImlzcyI6IklkZW50aXR5QVBJIiwiYXVkIjoiQ3J5cHRvQXBwVXNlcnMifQ.8gJwWAGbmGsiQU5nAraMJ_7XwtHB7tTsrX5ulLGqUok

{
  "Amount": 100
}
